PRODUCTS_PER_PAGE = 12

PRODUCT_UNIT_KILOGRAM = "kg"
PRODUCT_UNIT_TON = "ton"
PRODUCT_UNIT_PIECE = "piece"
PRODUCT_UNIT_LITER = "liter"
PRODUCT_UNIT_BOX = "box"

PRODUCT_UNIT_CHOICES = (
    (PRODUCT_UNIT_KILOGRAM, "кг"),
    (PRODUCT_UNIT_TON, "тонна"),
    (PRODUCT_UNIT_PIECE, "шт"),
    (PRODUCT_UNIT_LITER, "литр"),
    (PRODUCT_UNIT_BOX, "ящик"),
)
