COMPANY_TYPE_SUPPLIER = "supplier"
COMPANY_TYPE_BUYER = "buyer"

COMPANY_TYPE_CHOICES = (
    (COMPANY_TYPE_SUPPLIER, "Производитель"),
    (COMPANY_TYPE_BUYER, "Покупатель"),
)

INN_ALLOWED_LENGTHS = (10, 12)
OGRN_ALLOWED_LENGTHS = (13, 15)

EMAIL_VERIFICATION_TTL_MINUTES = 15
EMAIL_VERIFICATION_MAX_ATTEMPTS = 5
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_CODE_SPACE = 1_000_000
EMAIL_RESEND_COOLDOWN_SECONDS = 60

ANALYTICS_TOP_PRODUCTS_LIMIT = 5
ANALYTICS_TOP_SUPPLIERS_LIMIT = 6
ANALYTICS_TOP_REGIONS_LIMIT = 5
